site_name: "Каптерка инженера-программиста"
site_url: https://art-injener.github.io/
nav:
  - Home: index.md
  - Обо мне: about.md
  - МФ АС "Невод":
    - Техническое задание:
      - Введение: course/technical_task/intro.md
      - ТЗ: course/technical_task/technical_task.md

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ru
          name: Russian
          build: true
          site_name: "Каптерка инженера-программиста"
          default: true
theme:
  name: readthedocs
  analytics:
    gtag: G-GGLCHNTQ3Z
extra:
  generator: false
