site_name: "Каптерка инженера-программиста"
site_url: https://art-injener.github.io/
copyright: Copyright &copy; 2024 Артем Данильченко

nav:
  - Home: index.md
  - Обо мне: about.md
  - МФ АС "Невод":
    - Техническое задание:
      - Введение: course/technical_task/intro.md
      - ТЗ: course/technical_task/technical_task.md
    - Проектирование системы:
      - Введение: course/system_design/intro.md
      - База знаний: course/system_design/knowledge_base.md
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ru
          name: Russian
          build: true
          site_name: "Каптерка инженера-программиста"
          default: true
theme:
  name: material
  analytics:
    gtag: G-GGLCHNTQ3Z
  features:
    - navigation.footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/injener133
      name: Связаться со мной
  analytics:
    provider: google
    property: G-GGLCHNTQ3Z

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format